
default_install_hook_types: [pre-commit, pre-push]
default_stages:
  - pre-commit
default_language_version:
  python: python3.11
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.55.0
  hooks:
    - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.0
  hooks:
    - id: mypy
      args: ["--ignore-missing-imports"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/pycqa/flake8
  rev: v4.0.1
  hooks:
    - id: flake8

repo:
  - repo: local
    hooks:
      - id: iris-classification-hook
        name: Run Iris Classification
        entry: python iris_classification.py
        language: python
        types: [python]
        always_run: true

      
