name: Pre-commit checks

# Déclencher le workflow à chaque pull request ou push sur la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Installer Python et Pre-commit
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Utilisez la version de Python nécessaire

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit  # Installe Pre-commit

      # Étape 3: Exécuter Pre-commit sur le dépôt
      - name: Run Pre-commit
        run: |
          pre-commit run --all-files  # Exécute Pre-commit sur tous les fichiers
